### ISSUE TITLE
/Discord-QR-Code-Token-Info-Grabber/main.py", line 132, in <module>     logChannelPre = (data["log_channel_id"]) KeyError: 'log_channel_id'

### ISSUE THREAD

**Issue by Aomayan24** [developmentPluto/Discord-QR-Code-Token-Info-Grabber#3]
how do i fix /Discord-QR-Code-Token-Info-Grabber/main.py", line 132, in <module>
    logChannelPre = (data["log_channel_id"])
KeyError: 'log_channel_id'

**Comment by developmentPluto** [comment]
Are you running it within the directory?
eg.  `cd /Discord-QR-Code-Token-Info-Grabber/`

**Comment by developmentPluto** [comment]
closed due to lack of response and inability to recreate issue.
